"""
Django settings for 线上课程api project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g+g%6o0n)0ihwz4*8fis6khxtyo$u$^a6r-7$-9@m^m*2f1x&#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '线上课程api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '线上课程api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# 日志配置
LOGGING = {
    # python日志版本号
    'version': 1,
    # 是否禁用其他日志
    'disable_existing_loggers': False,
    # 记录日志格式
    # levelname  : 日志错误级别
    # asctime    : 出现时间
    # module     : 错误文件
    # process:d  : 错误进程号
    # thread:d   : 错误线程号
    # message    : 错误信息

    'formatters': {
        # 详细级别
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s',
        },
        # 简易级别
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s',
        },
    },
    # 过滤器(过滤日志信息)
    'filters': {
        # 过滤特殊参数 foo 转变成 bar
        # 'special': {
        #     '()': 'project.logging.SpecialFilter',
        #     'foo': 'bar',
        # },

        # 要DEBUG= TRUE 过滤掉调试时的日志
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    # 日志处理器
    'handlers': {
        # 终端
        'console': {
            'level': 'DEBUG',  # 等级
            'filters': ['require_debug_true'],  # 通过什么过滤
            'class': 'logging.StreamHandler',  # 输出到类文件对象等等
            'formatter': 'simple'  # 输出方式简易模式
        },

        # 文件
        'file': {
            # 记录最低的级别
            'level': 'INFO',
            # 日志位置，日志文件名，日志保存目录必须手动创建
            'filename': os.path.join(os.path.dirname(BASE_DIR), 'logs/线上课程.log'),
            # 通过什么类实现
            'class': 'logging.handlers.RotatingFileHandler',
            # 日志的最大值，这里我设置600M
            'maxBytes': 600 * 1024 * 1024,
            # 日志文件的数量，设置最大日志数量为10
            'backupCount': 10,
            # 日志格式：详细格式
            'formatter': 'verbose'
        }

        # 通过邮件通知管理员
        # 'mail_admins': {
        #     'level': 'ERROR',
        #     'class': 'django.utils.log.AdminEmailHandler',
        #     'filters': ['special']
        # }
    },
    # 日志对象
    'loggers': {
        'django': {  # 基于Django的日志配置
            'handlers': ['console', 'file'],  # 使用什么处理器
            'propagate': True,  # 是否让日志冒泡给其他日志处理系统
            # },
            # 'django.request': {
            #     'handlers': ['mail_admins'],
            #     'level': 'ERROR',
            #     'propagate': False,
            # },
            # 'myproject.custom': {
            #     'handlers': ['console', 'mail_admins'],
            #     'level': 'INFO',
            #     'filters': ['special']
            # }
        }
    }
}

# 异常错误配置
REST_FRAMEWORK = {
    # 异常处理
    'EXCEPTION_HANDLER': '线上课堂api.utils.exceptions.custom_exception_handler'
}