# Generated by Django 2.2.7 on 2019-11-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '学校风景轮播', 'verbose_name_plural': '学校风景轮播'},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='ly_banner',
        ),
    ]
