# Generated by Django 2.2.7 on 2019-11-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191121_1728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='gl_banner',
        ),
    ]
