# Generated by Django 2.2.7 on 2019-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191121_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='视频标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='host_video_image', verbose_name='视频封面名称')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否是站外链接')),
                ('remake', models.CharField(max_length=500, verbose_name='备注信息')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '热门视频',
                'verbose_name_plural': '热门视频',
                'db_table': 'gl_timer',
            },
        ),
    ]
