# Generated by Django 2.2.7 on 2019-11-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='remake',
            field=models.TextField(verbose_name='备注信息'),
        ),
    ]
