# Generated by Django 2.2.7 on 2019-12-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_host',
            field=models.BooleanField(default=False, verbose_name='是否推荐到热门视频'),
        ),
    ]
