# Generated by Django 2.2.7 on 2019-12-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courselesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='section_link',
            field=models.FileField(blank=True, help_text='若是video,填vid,若是文档，填写link', max_length=255, null=True, upload_to='', verbose_name='课时附件链接'),
        ),
    ]
