# Generated by Django 2.2.7 on 2019-12-10 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191210_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courseless_course', to='course.Course', verbose_name='专题课程'),
            preserve_default=False,
        ),
    ]
