# Generated by Django 2.2.7 on 2020-02-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostShortVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='视频名称')),
                ('file_url', models.FileField(upload_to='', verbose_name='视频地址')),
                ('focus_content', models.TextField(verbose_name='焦点内容')),
                ('video_time', models.CharField(max_length=64, verbose_name='视频时长')),
                ('video_img', models.ImageField(upload_to='', verbose_name='视频封面')),
                ('video_stauts', models.DateTimeField(blank=True, default=None, null=True, verbose_name='审核时间')),
                ('course_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseCategory', verbose_name='视频所属分类')),
                ('user_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传视频所属人')),
            ],
            options={
                'verbose_name': '热点短视频',
                'verbose_name_plural': '热点短视频',
                'db_table': 'gl_HostShortVideo',
            },
        ),
    ]
