# Generated by Django 2.2.7 on 2020-02-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostshortvideo',
            name='course_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.CourseCategory', verbose_name='视频所属分类'),
        ),
    ]
