# Generated by Django 2.2.7 on 2020-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200212_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostshortvideo',
            name='video_stauts',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '通过'), (2, '不通过')], default=0, verbose_name='审核状态'),
        ),
    ]
