# Generated by Django 2.2.7 on 2020-02-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20200217_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_play',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_watch',
            field=models.IntegerField(default=0, verbose_name='观看人数'),
        ),
    ]
