# Generated by Django 2.2.7 on 2019-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=500, verbose_name='风景图标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='学校风景图名字')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否是站外链接')),
                ('remark', models.TextField(verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '学校风景轮播',
                'verbose_name_plural': '学校风景轮播',
                'db_table': 'gl_banner',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=500, verbose_name='视频标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='host_video_image', verbose_name='视频封面名称')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否是站外链接')),
                ('remake', models.TextField(verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '热门视频',
                'verbose_name_plural': '热门视频',
                'db_table': 'gl_timer',
            },
        ),
    ]
